apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  projectID: trial-404919
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-provider-secret
      key: credentials
