apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-gke
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-container:v1.3.0
