apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  projectID: {{ .Values.providerConfig.projectID }}
  credentials:
    source: ImpersonateServiceAccount
    impersonateServiceAccount:
      name: crossplane-sa@{{ .Values.providerConfig.projectID }}.iam.gserviceaccount.com
