clusters:
  - name: dev
    values:
      harbour:
        core:
          replicas: 1
  - name: staging
    values:
      harbour:
        core:
          replicas: 2

# Example:
# clusters:
#   - name: dev
#     forProvider:
#       initialNodeCount: 3
#       location: europe-west1-a
#   - name: dev-2
#     forProvider:
#       initialNodeCount: 3
#       location: europe-west1-a
