{{- if .Values.clusterApplications.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-applications
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{ "'{{ .nameNormalized }}-applications'" }}
    spec:
      project: core
      source:
        repoURL: https://github.com/dom38/bootstrap-cloud.git
        targetRevision: main
        path: charts/2-applications
        helm:
          valueFiles:
            - {{ "'{{ .nameNormalized }}.yaml'" }}
      destination:
        server: {{ "'{{ .server }}'" }}
        namespace: harbour
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true 
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true

{{- end}}
