{{- if .Values.gkeClusters.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-clusters
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: core
  source:
    repoURL: https://github.com/dom38/bootstrap-cloud.git
    targetRevision: main
    path: charts/gke-cluster
    helm:
      values: |
        clusters:
        {{- range $path, $_ :=  .Files.Glob  "cluster-definitions/*.yaml" }}
          - {{ $yaml := $.Files.Get $path | fromYaml -}}
            name: {{ $yaml.global.clusterName }}
            forProvider: 
              {{- $yaml.global.forProvider | toYaml | nindent 14 }}
        {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

{{- end}}
