apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbour
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  source:
    repoURL: https://helm.goharbor.io
    targetRevision:  1.15.0
    chart: harbor
    helm:
      values: |
        externalURL: https://harbour.local.dev
        adminPassword: "test"
        expose:
          type: loadBalancer
          tls:
            auto:
              commonName: harbour.local.dev

  destination:
    server: https://kubernetes.default.svc
    namespace: harbour

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3
