apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dagster
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git: 
      repoURL: https://github.com/dom38/bootstrap-cloud.git
      revision: main
      files:
        - path: 1-core-cluster/core/cluster-definitions/*.yaml

  template:
    metadata:
      name: {{ "'{{ .global.clusterName }}-dagster'" }}
    spec:
      project: core
      source:
        repoURL: https://dagster-io.github.io/helm
        targetRevision:  1.7.10
        chart: dagster
        helm:
          values: {{ "'{{ .applicationValues.harbour | toJson }}'" }}
      destination:
        name: {{ "'{{ .global.clusterName }}-cluster'" }}
        namespace: dagster
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true 
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
