apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{ "'{{ .nameNormalized }}-crossplane'" }}
    spec:
      project: core
      source:
        repoURL: https://charts.crossplane.io/stable
        targetRevision:  1.16.0
        chart: crossplane
      destination:
        server: {{ "'{{ .server }}'" }}
        namespace: crossplane-system
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true 
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
