apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: harbour
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git: 
          repoURL: https://github.com/dom38/bootstrap-cloud.git
          revision: main
          files:
            - path: charts/gke-cluster/values.yaml
      - list:
          elementsYaml: {{ "'{{ .clusters | toJson }}'" }}

  template:
    metadata:
      name: {{ "'{{ .name }}-harbour'" }}
    spec:
      project: core
      source:
        repoURL: https://helm.goharbor.io
        targetRevision:  1.15.0
        chart: harbor
        helm:
          valuesObject: {{ "'{{ .values.harbour }}'" }}
      destination:
        server: {{ "'{{ .name }}-cluster'" }}
        namespace: harbour
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true 
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
