apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{ "'{{ .nameNormalized }}-ingress-nginx'" }}
    spec:
      project: core
      source:
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision:  4.10.1
        chart: ingress-nginx
      destination:
        server: {{ "'{{ .server }}'" }}
        namespace: ingress-nginx
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true 
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
