apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{ "'{{ .nameNormalized }}-keda'" }}
    spec:
      project: core
      source:
        repoURL: https://kedacore.github.io/charts
        targetRevision:  2.14.2
        chart: keda
      destination:
        server: {{ "'{{ .server }}'" }}
        namespace: keda
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true 
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
