apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{ "'{{ .nameNormalized }}-eso'" }}
    spec:
      project: core
      source:
        repoURL: https://charts.external-secrets.io
        targetRevision:  0.9.19
        chart: external-secrets
      destination:
        server: {{ "'{{ .server }}'" }}
        namespace: external-secrets-operator
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true 
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
