apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: harbour
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'harbour'
    spec:
      project: core
      source:
        repoURL: https://helm.goharbor.io
        targetRevision:  1.15.0
        chart: harbor
      destination:
        server: '{{server}}'
        namespace: harbour
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true 
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
